### ISSUE TITLE
Compilator fails at permissions

### ISSUE THREAD

**Issue by vicentefelipechile** [conaticus/FileExplorer#23]
The compiler fails because it does not have the necessary permissions to perform the compilation

![imagen](https://github.com/conaticus/FileExplorer/assets/70909800/c88332ad-1d65-4c84-8062-55061f4a30ea)

<hr>

To fix this, you have to configure your repository like this

![imagen](https://github.com/conaticus/FileExplorer/assets/70909800/4c8aea37-f7c8-4fdd-8526-ea73033e141a)

![imagen](https://github.com/conaticus/FileExplorer/assets/70909800/49d866ca-e52e-49fa-bf9c-3e7193c0825d)

**Comment by conaticus** [comment]
Yep that works now. Thanks for your help!
