### ISSUE TITLE
Only create build executables on main branch

### ISSUE THREAD

**Issue by conaticus** [conaticus/FileExplorer#24]
Currently the workflow creates a new release every time the dev branch is updated. It would make sense that these executables are only built when changes are made to the main branch.

**Comment by conaticus** [comment]
@vicentefelipechile Hey do you reckon you would be able to do this? I have created a main branch and made it the default.

**Comment by vicentefelipechile** [comment]
Ok! i opened a pull requests to compile the main branch and added a formatting version

**Comment by ProtogenDelta** [comment]
Can this be closed as per #25?
