### ISSUE TITLE
Hint: Create a release for macOS and for Linux

### ISSUE THREAD

**Issue by AntonioBerna** [conaticus/FileExplorer#65]
Even macOS and Linux have difficulty searching for information through the Finder when the computer's SSD is almost completely full, just as on Windows. It would be useful to extend this interesting project so that it is cross-platform so that anyone can use it as a replacement for what is generally provided

**Comment by 0xanassff** [comment]
i mean, cli is enough isn't it? plocate provide a very fast search time in the whole disk, ls is fine for getting files basic enough

**Comment by AntonioBerna** [comment]
Yes indeed on Linux there would be no need for it at all, however on macOS it would be interesting because Spotlight is efficient only for applications

**Comment by RaphGL** [comment]
Linux does indeed already have file managers and search tools that are very fast and give you back results nearly instantaneously or in seconds tops.

The project already support Linux and MacOS (though it is a very WIP project), simply the guy that wrote the github action did not make it create a linux and macos build).

**Comment by AntonioBerna** [comment]
> Linux does indeed already have file managers and search tools that are very fast and give you back results nearly instantaneously or in seconds tops.
> 
> The project already support Linux and MacOS (though it is a very WIP project), simply the guy that wrote the github action did not make it create a linux and macos build).

Thank you for the information, let's say that this issue was more as you say to also provide releases for macOS and Linux

**Comment by conaticus** [comment]
Linux & Mac have a lot of bugs but if we continue the project we will add support for these.
