### ISSUE TITLE
Latest .msi doesn't get installed on Windows 7

### ISSUE THREAD

**Issue by FWone** [conaticus/FileExplorer#73]
Don't blame me for having an outdated system
It's just i wanted to try it out and all it pulls out this:
![CaptureEroor](https://github.com/conaticus/FileExplorer/assets/87392446/488a6f46-39ea-4b45-8dc1-1c84f807225f)

**Comment by ProtogenDelta** [comment]
Windows 7 is officially out of support as of January 14, 2020.

Unless you can figure out how to fix the issue yourself, this is going to be marked as won't fix.

**Comment by Gofive** [comment]
> Don't blame me for having an outdated system It's just i wanted to try it out and all it pulls out this: ![CaptureEroor](https://user-images.githubusercontent.com/87392446/252081327-488a6f46-39ea-4b45-8dc1-1c84f807225f.PNG)

You should install webview2 on your Windows 7 . Tauri run relay on webview2 runtime.
